import './scss/style.scss';
import './ts/year';
import './ts/slider';
import './ts/show-animations';
import './ts/modals';
import './ts/city';
import './ts/dropdowns';
import './ts/setup-forms';
import './ts/f5leads';
